## John Shanahan

# -- Pyenv
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"

# -- Set terminal to VIMode
set -o vi
export EDITOR=vim

# -- If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# -- History
HISTCONTROL=ignoreboth
shopt -s histappend
HISTSIZE=5000
HISTFILESIZE=5000

# -- Check the window size after each command
shopt -s checkwinsize

# -- Make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# -- Set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# -- Color
force_color_prompt=yes

# -- PS1
export PS1="\W > \[$(tput sgr0)\]"

# -- Aliases
if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# -- Git autocomplete
if [ -f ~/.git-completion.bash ]; then
  . ~/.git-completion.bash
fi

# -- Enable programmable completion
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

