""""""""""""""""""""
" Vundle 
""""""""""""""""""""
set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" ---

"Let Vundle manage itself
Plugin 'gmarik/vundle'

"Put Github plugins here:
Plugin 'scrooloose/syntastic'
Plugin 'flazz/vim-colorschemes'
" ---

call vundle#end()
filetype plugin indent on
""""""""""""""""""""

" RetCurse - Return cursor to last known position
function! ResCur()
  if line("'\"") <= line("$")
    normal! g`"
    return 1
  endif
endfunction
augroup resCur
  autocmd!
  autocmd BufWinEnter * call ResCur()
augroup END
""""""""""""""""""""


" Main Settings
set number
syntax on
colorscheme molokai                     " Set color scheme
set background=dark
cmap w!! %!sudo tee > /dev/null %;      " Force save files that require root
let mapleader = ","                     " Set map leader to ','
let g:mapleader = ","
set encoding=utf8                       " Sets utf8 as standard encoding
set history=500                         " 500 commands back
set undofile                            " Persistant undo
set undolevels=500                      " Undo's
set undoreload=500
set undodir=~/.vim/backup/              " Set a backup directory for vim
set backupdir=~/.vim/backup/
set directory=~/.vim/backup/
set backspace=2                         " Fix broken backspace in 7.4
set scrolloff=10                        " Number of lines to show around cursor
set sidescrolloff=10
" Changes bgcolor after the 120th column
execute "set colorcolumn=".join(range(121,335), ',') 	
:hi ColorColumn ctermbg=black guibg=black               " Sets colorcolumn to black
set hlsearch                            " Highlight search terms
set laststatus=2                        " Always show statusline
set visualbell                          " Turn off bell
set ttyfast
set lazyredraw
set showcmd                             " In status bar, show incomlete commands as they are typed
set ruler                               " Always display the current cursor pos. in the status bar.
set clipboard=unnamed                   " Yank to system clipboard by default
set smartindent
set tabstop=4
set shiftwidth=4
set expandtab
set mouse=a                             " Mouse scroll
set splitbelow
set autoread                            " Automatically re-read files changed outside of Vim.

""""""""""""""""""""
" Aliases
""""""""""""""""""""
nnoremap <leader>w :w<cr>               " Fast save
nnoremap <leader>nt :NERDTree<cr>       " Fast NERDTree
nnoremap <leader>q :q<cr>               " Fast q
nnoremap <leader>wq :wq<cr>             " Fast wq
inoremap jj <Esc>                       " Remap 'jj' to escape in insert mode

" Close nerdtree if nt is the last window open
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

" Vundle Help
""""""""""""""""""""
" :PluginList		-list configured plugins
" :PluginInstall	-install plugins
" :PluginUpdate     -Update Plugins
" :PluginSearch foo	-search for foo
" :PluginClean  	-confirm removal of unused plugins
"
" Added PluginInstall alias to bashrc:
" alias PluginInstall='vim +PluginInstall +qall'
" Use '$ PluginInstall' to install Vundle plugins
"
" Added PluginUpdate alias to bashrc:
" alias PluginUpdate='vim +PluginUpdate +qall'
" Use '$ PluginUpdate' to install Vundle plugins
"
" see :h vundle for more details
" comments after Bundle are allowed
" INSTALL WITH $ git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim
