" .vimrc
" John Shanahan
" shanahan.jrs@gmail.com
" github.com/shanahanjrs


""""""""""""""""""""
" Vundle 
""""""""""""""""""""
" Required
set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" ---

"Let Vundle manage itself
Plugin 'gmarik/vundle'
" ---

"Put Github plugins here:
Plugin 'scrooloose/syntastic'
Plugin 'Yggdroot/indentLine'
Plugin 'tpope/vim-fugitive'
Plugin 'bling/vim-airline'
Plugin 'scrooloose/nerdtree'
Plugin 'shougo/vimproc'
Plugin 'shougo/vimshell'
Plugin 'flazz/vim-colorschemes'
" ---

call vundle#end()
filetype plugin indent on
""""""""""""""""""""

""""""""""""""""""""
" RetCurse - Return cursor to last known position
""""""""""""""""""""
function! ResCur()
  if line("'\"") <= line("$")
    normal! g`"
    return 1
  endif
endfunction
augroup resCur
  autocmd!
  autocmd BufWinEnter * call ResCur()
augroup END
""""""""""""""""""""

""""""""""""""""""""
" Make Windows compatible (gross)
""""""""""""""""""""
if has('win32') || has('win64')
	set runtimepath=$HOME/.vim,$VIM/vimfiles,$VIMRUNTIME,$VIM/vimfiles/\
after,$HOME/.vim/after
endif

""""""""""""""""""""
" Main Settings
""""""""""""""""""""

" Set color scheme
colorscheme molokai

" Force save files that require root
cmap w!! %!sudo tee > /dev/null %

" Set map leader to ','
let mapleader = ","
let g:mapleader = ","

" Sets utf8 as standard encoding
set encoding=utf8

" 500 commands back
set history=500

" Persistant undo
set undofile

" Undo's
set undolevels=500

" Undo buffer
set undoreload=500

" Set a backup directory for vim
set undodir=~/.vim/backup/
set backupdir=~/.vim/backup/
set directory=~/.vim/backup/

" Fix broken backspace in 7.4
set backspace=2

" Number of lines to show around cursor
set scrolloff=10
set sidescrolloff=10

" Show line numbers
set number

" Turn on syntax highlighting
syntax on

" Assumes a dark bg
set background=dark

" Changes bgcolor after the 80th column
execute "set colorcolumn=" . join(range(81,335), ',') 	

" Sets colorcolumn to black
:hi ColorColumn ctermbg=black guibg=black

" Makes anything past 80 col red/white
highlight OverLength ctermbg=red ctermfg=white guibg=#592929
match OverLength /\%80v.\+/

" Highlight search terms
set hlsearch

" Always show statusline
set laststatus=2

" Turn off bell
set visualbell

" Term things
set ttyfast
set lazyredraw

" In status bar, show incomlete commands as they are typed
set showcmd

" Turn off spell check
set nospell

" Always display the current cursor pos. in the status bar.
set ruler

" Yank to system clipboard by default
set clipboard=unnamed

" Some extra indentation magic...
set smartindent
set tabstop=4
set shiftwidth=4
set expandtab

" For more natural looking splitting
set splitbelow

" Automatically re-read files changed outside of Vim.
set autoread

""""""""""""""""""""
" Aliases
""""""""""""""""""""
" Fast save
nnoremap <leader>w :w<cr>

" Fast NERDTree
nnoremap <leader>nt :NERDTree<cr>

" Fast q
nnoremap <leader>q :q<cr>

" Fast wq
nnoremap <leader>wq :wq<cr>

" Fast VimShell
nnoremap <leader>vs :VimShell<cr>

" Remap 'jj' to escape in insert mode
inoremap jj <Esc>

""""""""""""""""""""
" Help
""""""""""""""""""""

""""""""""""""""""""
" Vundle Help
""""""""""""""""""""
" :PluginList		-list configured plugins
" :PluginInstall	-install plugins
" :PluginUpdate     -Update Plugins
" :PluginSearch foo	-search for foo
" :PluginClean  	-confirm removal of unused plugins
"
" Added PluginInstall alias to bashrc:
" alias PluginInstall='vim +PluginInstall +qall'
" Use '$ PluginInstall' to install Vundle plugins
"
" Added PluginUpdate alias to bashrc:
" alias PluginUpdate='vim +PluginUpdate +qall'
" Use '$ PluginUpdate' to install Vundle plugins
"
" see :h vundle for more details
" comments after Bundle are allowed
" INSTALL WITH $ git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim
""""""""""""""""""""
